// --- Auto-Generated By Unplugin-Export-Collector ---

const __UnExportList = ['createMeta', 'createPromiseQueue', 'flow', 'groupBy', 'isArray', 'isBoolean', 'isDate', 'isDef', 'isFunction', 'isInRange', 'isNull', 'isNumber', 'isObject', 'isPromise', 'isRegExp', 'isString', 'isUndefined', 'noop', 'sleep', 'toArray', 'toLF', 'toNumber', 'toPromise', 'uniq'] as const

/**
 * @returns Call in `imports` option of `unplugin-auto-import`.
 */
export default function autoImport(map?: Partial<{ [K in typeof __UnExportList[number]]: string }>): Record<string, (string | [string, string])[]> {
  return {
    '@s3xysteak/utils': __UnExportList.map(v => map && map[v] ? [v, map[v]] as [string, string] : v),
  }
}

// --- Auto-Generated By Unplugin-Export-Collector ---
