export * from '@antfu/utils'

export * from './core/is'
export * from './core/number'
export * from './core/base'
export * from './core/fp'
export * from './core/types'
export * from './core/promise'
export * from './core/defineRequest/axiosFactory'

// --- Auto-Generated By Unplugin-Export-Collector ---

const exportList = ["createPromiseQueue","flow","isArray","isBoolean","isDate","isDef","isFunction","isInRange","isNull","isNumber","isObject","isRegExp","isString","isUndefined","sleep","toLF","toNumber"] as const

export type UnpluginExportCollectorAutoImportMap = { [K in typeof exportList[number]]: string }
export function autoImport(map?: Partial<UnpluginExportCollectorAutoImportMap>): Record<string, (string | [string, string])[]> {
  return {
    '@s3xysteak/utils': exportList.map(v => map && map[v] ? [v, map[v]] as [string, string] : v),
  }
}

// --- Auto-Generated By Unplugin-Export-Collector ---
